//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ErrorMessages", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Erro da aplicação.&lt;/p&gt;&lt;p&gt;Os administradores do website foram automaticamente notificados sobre este problema.&lt;/p&gt;&lt;p&gt;Por favor tente mais tarde.&lt;/p&gt;.
        /// </summary>
        internal static string appError {
            get {
                return ResourceManager.GetString("appError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Erro no acesso à base de dados.&lt;/p&gt;&lt;p&gt;Não foi possível obter dados sobre o(s) registo(s) pretendido(s).&lt;/p&gt;&lt;p&gt;Os administradores do website foram automaticamente notificados sobre este problema.&lt;/p&gt;&lt;p&gt;Por favor tente mais tarde.&lt;/p&gt;.
        /// </summary>
        internal static string dbaError {
            get {
                return ResourceManager.GetString("dbaError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível eliminar o(s) registo(s)..
        /// </summary>
        internal static string deleteError {
            get {
                return ResourceManager.GetString("deleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endereço de correio eletrónico duplicado.
        /// </summary>
        internal static string duplicatedEmail {
            get {
                return ResourceManager.GetString("duplicatedEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilizador duplicado.
        /// </summary>
        internal static string duplicatedUser {
            get {
                return ResourceManager.GetString("duplicatedUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível inserir registo..
        /// </summary>
        internal static string insertError {
            get {
                return ResourceManager.GetString("insertError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endereço de correio eletrónico inválido.
        /// </summary>
        internal static string invalidEmail {
            get {
                return ResourceManager.GetString("invalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pelo menos um parâmetro deve conter um valor.
        /// </summary>
        internal static string invalidParameters {
            get {
                return ResourceManager.GetString("invalidParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha de identificação inválida.
        /// </summary>
        internal static string invalidPassword {
            get {
                return ResourceManager.GetString("invalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registo não efetuado. Formato de senha d eidentificação inválido. A senha deve ter pelo menos 6 caracteres e deve ter pelo menos um caractere não alfanumérico.
        /// </summary>
        internal static string invalidPasswordFormat {
            get {
                return ResourceManager.GetString("invalidPasswordFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registo inválido.
        /// </summary>
        internal static string invalidRecord {
            get {
                return ResourceManager.GetString("invalidRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credenciais de utilizador inválidas.
        /// </summary>
        internal static string loginFailureText {
            get {
                return ResourceManager.GetString("loginFailureText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilizador sem permissões para alterar o registo.
        /// </summary>
        internal static string noChangePermissions {
            get {
                return ResourceManager.GetString("noChangePermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senhas de identificação não coincidem..
        /// </summary>
        internal static string passwordsMissmatch {
            get {
                return ResourceManager.GetString("passwordsMissmatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo de valor obrigatório..
        /// </summary>
        internal static string requiredFieldError {
            get {
                return ResourceManager.GetString("requiredFieldError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Erro no servidor de base de dados.&lt;/p&gt;&lt;p&gt;Não foi possível obter dados sobre o(s) registo(s) pretendido(s).&lt;/p&gt;&lt;p&gt;Os administradores do website foram automaticamente notificados sobre este problema.&lt;/p&gt;&lt;p&gt;Por favor tente mais tarde.&lt;/p&gt;.
        /// </summary>
        internal static string sqlError {
            get {
                return ResourceManager.GetString("sqlError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível actualizador o registo..
        /// </summary>
        internal static string updateError {
            get {
                return ResourceManager.GetString("updateError", resourceCulture);
            }
        }
    }
}
